# this is an official Python runtime, used as the parent image
FROM python:3.8-slim-buster

# set the working directory in the container to /app
WORKDIR /app

# add the current directory to the container as /app
ADD ./index.py /app

# execute everyone's favorite pip command, pip install -r
RUN pip install --trusted-host pypi.python.org bottle redis

# unblock port 80 for the Bottle app to run on
EXPOSE 8000

# execute the Flask app
CMD ["python", "index.py"]